# Disable sudo to speed up the build
sudo: false

# Set the build language to Python
language: python

python:
  - 3.6
  - 2.7

# Install the codecov pip dependency
install:
  - pip install codecov
  - pip install -r requirements.txt

# Run the unit test
script:
  - coverage run -m unittest discover

# Push the results back to codecov
after_success:
  - codecov
